export const data = [
  {
    orgId: "falcon-metrics-dev",
    datasourceId: "f0399cdc8c2263fd5f3bb32c0d98b983",
    workflowId: "falcon-metrics-dev.10000.epic",
    workItemTypeId: "falcon-metrics-dev.epic",
    datasourceWorkItemId: "10000",
    archived: false,
    projectId: "10000",
    serviceLevelExpectationInDays: 30,
    level: "Portfolio",
    isDistinct: false,
    steps: [
      {
        name: "Delivery",
        type: "active",
        average: 47.13203703703704,
        "50thPercentile": 54.48,
        "85thPercentile": 59.99,
        "98thPercentile": 89.34,
        totalTime: 377.0562962962963,
        currentWipCount: 6,
        totalWipTime: 148.27502314814816,
        items: [
          {
            workItemId: "FLO-2110",
            workItemTitle: "Cycle Time Analysis / Bottleneck Finder",
            workItemType: "Epic",
            timeInCurrentState: 2.7372916666666667,
          },
          {
            workItemId: "FLO-4385",
            workItemTitle:
              "Maintain Platform Stability and usability (no P1, P2, P3)",
            workItemType: "Initiative",
            timeInCurrentState: 116.56987268518519,
          },
          {
            workItemId: "FLO-4571",
            workItemTitle:
              "Increase our ARR by $40,000 before January 1st, at least 50% of this from existing customers.",
            workItemType: "Initiative",
            timeInCurrentState: 18.832175925925927,
          },
          {
            workItemId: "FLO-4587",
            workItemTitle:
              "remove customer reliance on our team for building queries in Falcon Metrics",
            workItemType: "Epic",
            timeInCurrentState: 2.7371412037037035,
          },
          {
            workItemId: "FLO-4589",
            workItemTitle:
              "Discover and implement the one enhancement that will make 3 of our customers love our product by November 30th",
            workItemType: "Epic",
            timeInCurrentState: 4.6613541666666665,
          },
          {
            workItemId: "FLO-4590",
            workItemTitle:
              "Implement TypeScript checks on the deployment pipeline by November 30th",
            workItemType: "Epic",
            timeInCurrentState: 2.7371875,
          },
        ],
      },
      {
        name: "Waiting",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 4,
        totalWipTime: 57.15295138888889,
        items: [
          {
            workItemId: "FLO-2109",
            workItemTitle: "Cycle time Scatterplot Front end MVP",
            workItemType: "Feature",
            timeInCurrentState: 7.5572337962962965,
          },
          {
            workItemId: "FLO-4373",
            workItemTitle: "Manage teams and individuals",
            workItemType: "Epic",
            timeInCurrentState: 43.70934027777778,
          },
          {
            workItemId: "FLO-4636",
            workItemTitle:
              "Demand vs Capacity the number are not consistent for the time period when looked from annual POV",
            workItemType: "Bug",
            timeInCurrentState: 2.5536458333333334,
          },
          {
            workItemId: "FLO-4642",
            workItemTitle:
              "Industry benchmark for flow efficiency is following an incorrect logic.",
            workItemType: "Bug",
            timeInCurrentState: 3.3327314814814817,
          },
        ],
      },
      {
        name: "Done",
        type: "queue",
        average: 56.07183883101852,
        "50thPercentile": 64.62,
        "85thPercentile": 80.89,
        "98thPercentile": 96.21,
        totalTime: 448.57471064814814,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Discarded",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Rejected",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Outline_EDITED",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
    ],
  },
  {
    orgId: "falcon-metrics-dev",
    datasourceId: "f0399cdc8c2263fd5f3bb32c0d98b983",
    workflowId: "falcon-metrics-dev.10000.feature",
    workItemTypeId: "falcon-metrics-dev.feature",
    datasourceWorkItemId: "10032",
    archived: false,
    projectId: "10000",
    serviceLevelExpectationInDays: 30,
    level: "Portfolio",
    isDistinct: false,
    steps: [
      {
        name: "In Progress",
        type: "active",
        average: 8.65499503968254,
        "50thPercentile": 4.86,
        "85thPercentile": 14.05,
        "98thPercentile": 24.14,
        totalTime: 60.584965277777776,
        currentWipCount: 3,
        totalWipTime: 46.045,
        items: [
          {
            workItemId: "FLO-2715",
            workItemTitle:
              "Write the calculations using current wip scenario for scatterplot",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 4.656736111111111,
          },
          {
            workItemId: "FLO-4514",
            workItemTitle: "Implement SSO Authentication",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 36.7315625,
          },
          {
            workItemId: "FLO-4625",
            workItemTitle:
              "Write the calculations using current wip scenario for bottleneck indicator",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 4.656701388888889,
          },
        ],
      },
      {
        name: "Waiting",
        type: "queue",
        average: 5.979953703703703,
        "50thPercentile": 6.46,
        "85thPercentile": 7.88,
        "98thPercentile": 8.41,
        totalTime: 17.93986111111111,
        currentWipCount: 4,
        totalWipTime: 57.15295138888889,
        items: [
          {
            workItemId: "FLO-2109",
            workItemTitle: "Cycle time Scatterplot Front end MVP",
            workItemType: "Feature",
            timeInCurrentState: 7.5572337962962965,
          },
          {
            workItemId: "FLO-4373",
            workItemTitle: "Manage teams and individuals",
            workItemType: "Epic",
            timeInCurrentState: 43.70934027777778,
          },
          {
            workItemId: "FLO-4636",
            workItemTitle:
              "Demand vs Capacity the number are not consistent for the time period when looked from annual POV",
            workItemType: "Bug",
            timeInCurrentState: 2.5536458333333334,
          },
          {
            workItemId: "FLO-4642",
            workItemTitle:
              "Industry benchmark for flow efficiency is following an incorrect logic.",
            workItemType: "Bug",
            timeInCurrentState: 3.3327314814814817,
          },
        ],
      },
      {
        name: "Dev Complete",
        type: "queue",
        average: 2.791175925925926,
        "50thPercentile": 1.97,
        "85thPercentile": 5.23,
        "98thPercentile": 7.07,
        totalTime: 13.95587962962963,
        currentWipCount: 1,
        totalWipTime: 2.288148148148148,
        items: [
          {
            workItemId: "FLO-4646",
            workItemTitle:
              "In Fitness Criteria, historical view drill down for Fitness Level, Process Value and Flow Efficiency are showing same values",
            workItemType: "Bug",
            timeInCurrentState: 2.288148148148148,
          },
        ],
      },
      {
        name: "Deployed",
        type: "queue",
        average: 2.735605709876543,
        "50thPercentile": 2.59,
        "85thPercentile": 5.36,
        "98thPercentile": 6.02,
        totalTime: 16.413634259259258,
        currentWipCount: 8,
        totalWipTime: 482.9897800925926,
        items: [
          {
            workItemId: "FLO-4381",
            workItemTitle: "Initiative Updates MVP",
            workItemType: "Feature",
            timeInCurrentState: 100.6018287037037,
          },
          {
            workItemId: "FLO-4458",
            workItemTitle:
              "Refactor initiative updates and update form to properly use the context API set up",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88737268518518,
          },
          {
            workItemId: "FLO-4462",
            workItemTitle:
              "Add focus data to obeya and create new focus end point for portfolios",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88748842592592,
          },
          {
            workItemId: "FLO-4469",
            workItemTitle: "Fitness criteria not loading for obeyas",
            workItemType: "Bug",
            timeInCurrentState: 70.63383101851852,
          },
          {
            workItemId: "FLO-4470",
            workItemTitle: "Cost analysis",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88751157407407,
          },
          {
            workItemId: "FLO-4473",
            workItemTitle: "Focus Widget in Obeya Page (UI)",
            workItemType: "Feature",
            timeInCurrentState: 73.19569444444444,
          },
          {
            workItemId: "FLO-4513",
            workItemTitle:
              "Auto Avaliar is facing issues with timezone in performance checkpoints and initiaitves",
            workItemType: "Bug",
            timeInCurrentState: 37.496261574074076,
          },
          {
            workItemId: "FLO-4634",
            workItemTitle:
              "Mark unused contexts and components in VMO as deprecated",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 3.3997916666666668,
          },
        ],
      },
      {
        name: "Done",
        type: "queue",
        average: 79.80195932539684,
        "50thPercentile": 86.11,
        "85thPercentile": 94.98,
        "98thPercentile": 98.09,
        totalTime: 558.6137152777778,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Discarded",
        type: "queue",
        average: 9.04974537037037,
        "50thPercentile": 9.05,
        "85thPercentile": 9.05,
        "98thPercentile": 9.05,
        totalTime: 9.04974537037037,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Rejected",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
    ],
  },
  {
    orgId: "falcon-metrics-dev",
    datasourceId: "f0399cdc8c2263fd5f3bb32c0d98b983",
    workflowId: "falcon-metrics-dev.10000.initiative",
    workItemTypeId: "falcon-metrics-dev.initiative",
    datasourceWorkItemId: "10005",
    archived: false,
    projectId: "10000",
    serviceLevelExpectationInDays: 30,
    level: "Portfolio",
    isDistinct: false,
    steps: [
      {
        name: "Next Options",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Delivery",
        type: "active",
        average: 85.58627314814815,
        "50thPercentile": 85.59,
        "85thPercentile": 142.88,
        "98thPercentile": 164.16,
        totalTime: 171.1725462962963,
        currentWipCount: 6,
        totalWipTime: 148.27502314814816,
        items: [
          {
            workItemId: "FLO-2110",
            workItemTitle: "Cycle Time Analysis / Bottleneck Finder",
            workItemType: "Epic",
            timeInCurrentState: 2.7372916666666667,
          },
          {
            workItemId: "FLO-4385",
            workItemTitle:
              "Maintain Platform Stability and usability (no P1, P2, P3)",
            workItemType: "Initiative",
            timeInCurrentState: 116.56987268518519,
          },
          {
            workItemId: "FLO-4571",
            workItemTitle:
              "Increase our ARR by $40,000 before January 1st, at least 50% of this from existing customers.",
            workItemType: "Initiative",
            timeInCurrentState: 18.832175925925927,
          },
          {
            workItemId: "FLO-4587",
            workItemTitle:
              "remove customer reliance on our team for building queries in Falcon Metrics",
            workItemType: "Epic",
            timeInCurrentState: 2.7371412037037035,
          },
          {
            workItemId: "FLO-4589",
            workItemTitle:
              "Discover and implement the one enhancement that will make 3 of our customers love our product by November 30th",
            workItemType: "Epic",
            timeInCurrentState: 4.6613541666666665,
          },
          {
            workItemId: "FLO-4590",
            workItemTitle:
              "Implement TypeScript checks on the deployment pipeline by November 30th",
            workItemType: "Epic",
            timeInCurrentState: 2.7371875,
          },
        ],
      },
      {
        name: "Waiting",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 4,
        totalWipTime: 57.15295138888889,
        items: [
          {
            workItemId: "FLO-2109",
            workItemTitle: "Cycle time Scatterplot Front end MVP",
            workItemType: "Feature",
            timeInCurrentState: 7.5572337962962965,
          },
          {
            workItemId: "FLO-4373",
            workItemTitle: "Manage teams and individuals",
            workItemType: "Epic",
            timeInCurrentState: 43.70934027777778,
          },
          {
            workItemId: "FLO-4636",
            workItemTitle:
              "Demand vs Capacity the number are not consistent for the time period when looked from annual POV",
            workItemType: "Bug",
            timeInCurrentState: 2.5536458333333334,
          },
          {
            workItemId: "FLO-4642",
            workItemTitle:
              "Industry benchmark for flow efficiency is following an incorrect logic.",
            workItemType: "Bug",
            timeInCurrentState: 3.3327314814814817,
          },
        ],
      },
      {
        name: "Done",
        type: "queue",
        average: 42.87230902777778,
        "50thPercentile": 42.87,
        "85thPercentile": 59.7,
        "98thPercentile": 65.95,
        totalTime: 85.74461805555556,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Discarded",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Rejected",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Outline_EDITED",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
    ],
  },
  {
    orgId: "falcon-metrics-dev",
    datasourceId: "f0399cdc8c2263fd5f3bb32c0d98b983",
    workflowId: "falcon-metrics-dev.10000.bug",
    workItemTypeId: "falcon-metrics-dev.bug",
    datasourceWorkItemId: "10004",
    archived: false,
    projectId: "10000",
    serviceLevelExpectationInDays: 30,
    level: "Team",
    isDistinct: false,
    steps: [
      {
        name: "In Progress",
        type: "active",
        average: 1.8078562710437707,
        "50thPercentile": 0.22,
        "85thPercentile": 3.86,
        "98thPercentile": 8.54,
        totalTime: 99.43209490740739,
        currentWipCount: 3,
        totalWipTime: 46.045,
        items: [
          {
            workItemId: "FLO-2715",
            workItemTitle:
              "Write the calculations using current wip scenario for scatterplot",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 4.656736111111111,
          },
          {
            workItemId: "FLO-4514",
            workItemTitle: "Implement SSO Authentication",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 36.7315625,
          },
          {
            workItemId: "FLO-4625",
            workItemTitle:
              "Write the calculations using current wip scenario for bottleneck indicator",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 4.656701388888889,
          },
        ],
      },
      {
        name: "Waiting",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 4,
        totalWipTime: 57.15295138888889,
        items: [
          {
            workItemId: "FLO-2109",
            workItemTitle: "Cycle time Scatterplot Front end MVP",
            workItemType: "Feature",
            timeInCurrentState: 7.5572337962962965,
          },
          {
            workItemId: "FLO-4373",
            workItemTitle: "Manage teams and individuals",
            workItemType: "Epic",
            timeInCurrentState: 43.70934027777778,
          },
          {
            workItemId: "FLO-4636",
            workItemTitle:
              "Demand vs Capacity the number are not consistent for the time period when looked from annual POV",
            workItemType: "Bug",
            timeInCurrentState: 2.5536458333333334,
          },
          {
            workItemId: "FLO-4642",
            workItemTitle:
              "Industry benchmark for flow efficiency is following an incorrect logic.",
            workItemType: "Bug",
            timeInCurrentState: 3.3327314814814817,
          },
        ],
      },
      {
        name: "Dev Complete",
        type: "queue",
        average: 1.3339797278338943,
        "50thPercentile": 0.58,
        "85thPercentile": 3.41,
        "98thPercentile": 4.54,
        totalTime: 44.02133101851851,
        currentWipCount: 1,
        totalWipTime: 2.288148148148148,
        items: [
          {
            workItemId: "FLO-4646",
            workItemTitle:
              "In Fitness Criteria, historical view drill down for Fitness Level, Process Value and Flow Efficiency are showing same values",
            workItemType: "Bug",
            timeInCurrentState: 2.288148148148148,
          },
        ],
      },
      {
        name: "Deployed",
        type: "queue",
        average: 1.0365562169312168,
        "50thPercentile": 0.18,
        "85thPercentile": 2.79,
        "98thPercentile": 4.41,
        totalTime: 36.27946759259259,
        currentWipCount: 8,
        totalWipTime: 482.9897800925926,
        items: [
          {
            workItemId: "FLO-4381",
            workItemTitle: "Initiative Updates MVP",
            workItemType: "Feature",
            timeInCurrentState: 100.6018287037037,
          },
          {
            workItemId: "FLO-4458",
            workItemTitle:
              "Refactor initiative updates and update form to properly use the context API set up",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88737268518518,
          },
          {
            workItemId: "FLO-4462",
            workItemTitle:
              "Add focus data to obeya and create new focus end point for portfolios",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88748842592592,
          },
          {
            workItemId: "FLO-4469",
            workItemTitle: "Fitness criteria not loading for obeyas",
            workItemType: "Bug",
            timeInCurrentState: 70.63383101851852,
          },
          {
            workItemId: "FLO-4470",
            workItemTitle: "Cost analysis",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88751157407407,
          },
          {
            workItemId: "FLO-4473",
            workItemTitle: "Focus Widget in Obeya Page (UI)",
            workItemType: "Feature",
            timeInCurrentState: 73.19569444444444,
          },
          {
            workItemId: "FLO-4513",
            workItemTitle:
              "Auto Avaliar is facing issues with timezone in performance checkpoints and initiaitves",
            workItemType: "Bug",
            timeInCurrentState: 37.496261574074076,
          },
          {
            workItemId: "FLO-4634",
            workItemTitle:
              "Mark unused contexts and components in VMO as deprecated",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 3.3997916666666668,
          },
        ],
      },
      {
        name: "Done",
        type: "queue",
        average: 40.35277258939974,
        "50thPercentile": 32.19,
        "85thPercentile": 63.05,
        "98thPercentile": 95.88,
        totalTime: 2340.460810185185,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Discarded",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Rejected",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
    ],
  },
  {
    orgId: "falcon-metrics-dev",
    datasourceId: "f0399cdc8c2263fd5f3bb32c0d98b983",
    workflowId: "falcon-metrics-dev.10000.enabler-and-tech-debt",
    workItemTypeId: "falcon-metrics-dev.enabler-and-tech-debt",
    datasourceWorkItemId: "10006",
    archived: false,
    projectId: "10000",
    serviceLevelExpectationInDays: 7,
    level: "Team",
    isDistinct: false,
    steps: [
      {
        name: "In Progress",
        type: "active",
        average: 9.143408564814816,
        "50thPercentile": 4.78,
        "85thPercentile": 20.72,
        "98thPercentile": 28.33,
        totalTime: 91.43408564814816,
        currentWipCount: 3,
        totalWipTime: 46.045,
        items: [
          {
            workItemId: "FLO-2715",
            workItemTitle:
              "Write the calculations using current wip scenario for scatterplot",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 4.656736111111111,
          },
          {
            workItemId: "FLO-4514",
            workItemTitle: "Implement SSO Authentication",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 36.7315625,
          },
          {
            workItemId: "FLO-4625",
            workItemTitle:
              "Write the calculations using current wip scenario for bottleneck indicator",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 4.656701388888889,
          },
        ],
      },
      {
        name: "Waiting",
        type: "queue",
        average: 22.293229166666666,
        "50thPercentile": 22.29,
        "85thPercentile": 22.29,
        "98thPercentile": 22.29,
        totalTime: 22.293229166666666,
        currentWipCount: 4,
        totalWipTime: 57.15295138888889,
        items: [
          {
            workItemId: "FLO-2109",
            workItemTitle: "Cycle time Scatterplot Front end MVP",
            workItemType: "Feature",
            timeInCurrentState: 7.5572337962962965,
          },
          {
            workItemId: "FLO-4373",
            workItemTitle: "Manage teams and individuals",
            workItemType: "Epic",
            timeInCurrentState: 43.70934027777778,
          },
          {
            workItemId: "FLO-4636",
            workItemTitle:
              "Demand vs Capacity the number are not consistent for the time period when looked from annual POV",
            workItemType: "Bug",
            timeInCurrentState: 2.5536458333333334,
          },
          {
            workItemId: "FLO-4642",
            workItemTitle:
              "Industry benchmark for flow efficiency is following an incorrect logic.",
            workItemType: "Bug",
            timeInCurrentState: 3.3327314814814817,
          },
        ],
      },
      {
        name: "Dev Complete",
        type: "queue",
        average: 3.2402662037037038,
        "50thPercentile": 3.24,
        "85thPercentile": 4.73,
        "98thPercentile": 5.28,
        totalTime: 6.4805324074074075,
        currentWipCount: 1,
        totalWipTime: 2.288148148148148,
        items: [
          {
            workItemId: "FLO-4646",
            workItemTitle:
              "In Fitness Criteria, historical view drill down for Fitness Level, Process Value and Flow Efficiency are showing same values",
            workItemType: "Bug",
            timeInCurrentState: 2.288148148148148,
          },
        ],
      },
      {
        name: "Deployed",
        type: "queue",
        average: 0.00004050925925925926,
        "50thPercentile": 0,
        "85thPercentile": 0,
        "98thPercentile": 0,
        totalTime: 0.00008101851851851852,
        currentWipCount: 8,
        totalWipTime: 482.9897800925926,
        items: [
          {
            workItemId: "FLO-4381",
            workItemTitle: "Initiative Updates MVP",
            workItemType: "Feature",
            timeInCurrentState: 100.6018287037037,
          },
          {
            workItemId: "FLO-4458",
            workItemTitle:
              "Refactor initiative updates and update form to properly use the context API set up",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88737268518518,
          },
          {
            workItemId: "FLO-4462",
            workItemTitle:
              "Add focus data to obeya and create new focus end point for portfolios",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88748842592592,
          },
          {
            workItemId: "FLO-4469",
            workItemTitle: "Fitness criteria not loading for obeyas",
            workItemType: "Bug",
            timeInCurrentState: 70.63383101851852,
          },
          {
            workItemId: "FLO-4470",
            workItemTitle: "Cost analysis",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88751157407407,
          },
          {
            workItemId: "FLO-4473",
            workItemTitle: "Focus Widget in Obeya Page (UI)",
            workItemType: "Feature",
            timeInCurrentState: 73.19569444444444,
          },
          {
            workItemId: "FLO-4513",
            workItemTitle:
              "Auto Avaliar is facing issues with timezone in performance checkpoints and initiaitves",
            workItemType: "Bug",
            timeInCurrentState: 37.496261574074076,
          },
          {
            workItemId: "FLO-4634",
            workItemTitle:
              "Mark unused contexts and components in VMO as deprecated",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 3.3997916666666668,
          },
        ],
      },
      {
        name: "Done",
        type: "queue",
        average: 50.09651736111112,
        "50thPercentile": 55.24,
        "85thPercentile": 80.12,
        "98thPercentile": 90.84,
        totalTime: 500.9651736111112,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Discarded",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Rejected",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
    ],
  },
  {
    orgId: "falcon-metrics-dev",
    datasourceId: "f0399cdc8c2263fd5f3bb32c0d98b983",
    workflowId: "falcon-metrics-dev.10000.enhancement-and-optimisation",
    workItemTypeId: "falcon-metrics-dev.enhancement-and-optimisation",
    datasourceWorkItemId: "10007",
    archived: false,
    projectId: "10000",
    serviceLevelExpectationInDays: 10,
    level: "Portfolio",
    isDistinct: false,
    steps: [
      {
        name: "In Progress",
        type: "active",
        average: 6.447549189814815,
        "50thPercentile": 6,
        "85thPercentile": 14.03,
        "98thPercentile": 21.5,
        totalTime: 180.53137731481482,
        currentWipCount: 3,
        totalWipTime: 46.045,
        items: [
          {
            workItemId: "FLO-2715",
            workItemTitle:
              "Write the calculations using current wip scenario for scatterplot",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 4.656736111111111,
          },
          {
            workItemId: "FLO-4514",
            workItemTitle: "Implement SSO Authentication",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 36.7315625,
          },
          {
            workItemId: "FLO-4625",
            workItemTitle:
              "Write the calculations using current wip scenario for bottleneck indicator",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 4.656701388888889,
          },
        ],
      },
      {
        name: "Waiting",
        type: "queue",
        average: 2.1967939814814814,
        "50thPercentile": 2.2,
        "85thPercentile": 2.5,
        "98thPercentile": 2.61,
        totalTime: 4.393587962962963,
        currentWipCount: 4,
        totalWipTime: 57.15295138888889,
        items: [
          {
            workItemId: "FLO-2109",
            workItemTitle: "Cycle time Scatterplot Front end MVP",
            workItemType: "Feature",
            timeInCurrentState: 7.5572337962962965,
          },
          {
            workItemId: "FLO-4373",
            workItemTitle: "Manage teams and individuals",
            workItemType: "Epic",
            timeInCurrentState: 43.70934027777778,
          },
          {
            workItemId: "FLO-4636",
            workItemTitle:
              "Demand vs Capacity the number are not consistent for the time period when looked from annual POV",
            workItemType: "Bug",
            timeInCurrentState: 2.5536458333333334,
          },
          {
            workItemId: "FLO-4642",
            workItemTitle:
              "Industry benchmark for flow efficiency is following an incorrect logic.",
            workItemType: "Bug",
            timeInCurrentState: 3.3327314814814817,
          },
        ],
      },
      {
        name: "Dev Complete",
        type: "queue",
        average: 2.85253761574074,
        "50thPercentile": 0.64,
        "85thPercentile": 5.42,
        "98thPercentile": 15.39,
        totalTime: 45.64060185185184,
        currentWipCount: 1,
        totalWipTime: 2.288148148148148,
        items: [
          {
            workItemId: "FLO-4646",
            workItemTitle:
              "In Fitness Criteria, historical view drill down for Fitness Level, Process Value and Flow Efficiency are showing same values",
            workItemType: "Bug",
            timeInCurrentState: 2.288148148148148,
          },
        ],
      },
      {
        name: "Deployed",
        type: "queue",
        average: 1.8596905458089665,
        "50thPercentile": 0,
        "85thPercentile": 2.09,
        "98thPercentile": 15.15,
        totalTime: 35.334120370370364,
        currentWipCount: 8,
        totalWipTime: 482.9897800925926,
        items: [
          {
            workItemId: "FLO-4381",
            workItemTitle: "Initiative Updates MVP",
            workItemType: "Feature",
            timeInCurrentState: 100.6018287037037,
          },
          {
            workItemId: "FLO-4458",
            workItemTitle:
              "Refactor initiative updates and update form to properly use the context API set up",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88737268518518,
          },
          {
            workItemId: "FLO-4462",
            workItemTitle:
              "Add focus data to obeya and create new focus end point for portfolios",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88748842592592,
          },
          {
            workItemId: "FLO-4469",
            workItemTitle: "Fitness criteria not loading for obeyas",
            workItemType: "Bug",
            timeInCurrentState: 70.63383101851852,
          },
          {
            workItemId: "FLO-4470",
            workItemTitle: "Cost analysis",
            workItemType: "Enhancement & Optimisation",
            timeInCurrentState: 65.88751157407407,
          },
          {
            workItemId: "FLO-4473",
            workItemTitle: "Focus Widget in Obeya Page (UI)",
            workItemType: "Feature",
            timeInCurrentState: 73.19569444444444,
          },
          {
            workItemId: "FLO-4513",
            workItemTitle:
              "Auto Avaliar is facing issues with timezone in performance checkpoints and initiaitves",
            workItemType: "Bug",
            timeInCurrentState: 37.496261574074076,
          },
          {
            workItemId: "FLO-4634",
            workItemTitle:
              "Mark unused contexts and components in VMO as deprecated",
            workItemType: "Enabler & Tech Debt",
            timeInCurrentState: 3.3997916666666668,
          },
        ],
      },
      {
        name: "Done",
        type: "queue",
        average: 55.608131200396826,
        "50thPercentile": 58.57,
        "85thPercentile": 84.57,
        "98thPercentile": 85.77,
        totalTime: 1557.0276736111111,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Discarded",
        type: "queue",
        average: null,
        "50thPercentile": null,
        "85thPercentile": null,
        "98thPercentile": null,
        totalTime: 0,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
      {
        name: "Rejected",
        type: "queue",
        average: 3.0453703703703705,
        "50thPercentile": 3.05,
        "85thPercentile": 3.05,
        "98thPercentile": 3.05,
        totalTime: 3.0453703703703705,
        currentWipCount: 0,
        totalWipTime: 0,
        items: [],
      },
    ],
  },
];